// Rewrite the instructions in your own words

// Write the objectives and the tests
//first invent three variables as Acronyms, item and result
//then exert a prompt for "type any word of your choice"
//exert a title case for the Acronyms variable
// make a list from text with the acronyms variable with an space delimiter
//insert each item with a list of acronyms variable
//make a result of the item in a append text of acronyms variable to get first letter.

// Write the pseudocode
Create three variable 
set a prompt for the entry phrases
exert variables sets to each of the item to the list
create an append text for the items 
have a lsit of text with a delimiter 


// paste your JS generated by blockly below here
var result, acronyms, item;

function textToTitleCase(str) {
  return str.replace(/\S+/g,
      function(txt) {return txt[0].toUpperCase() + txt.substring(1).toLowerCase();});
}


result = '';
acronyms = window.prompt('enter your phrase');
acronyms = textToTitleCase(acronyms);
acronyms = acronyms.split(' ');
for (var item_index in acronyms) {
  item = acronyms[item_index];
  result += String(item.charAt(0));
}
window.alert(result);